name: Run Movie Bot Randomly (1–2hr gaps, all day)

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes (GitHub Actions limit)

jobs:
  ping-movie-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Random API Call with 1–2hr Gap Simulation
        run: |
          echo "🎰 Simulating 1–2 hour randomness..."

          # ~75% chance to skip this run
          CHANCE=$(( RANDOM % 4 ))
          if [ "$CHANCE" -ne 0 ]; then
            echo "🎲 Skipping this run for randomness. Try again in 15 mins."
            exit 0
          fi

          # Random delay between 15 to 45 minutes
          DELAY=$(( 900 + RANDOM % 1800 ))
          echo "⏱ Sleeping for $DELAY seconds (~$((DELAY / 60)) minutes)..."
          sleep $DELAY

          echo "🚀 Calling the movie bot API..."

          RESPONSE=$(curl -s -w "\nStatus: %{http_code}" "https://movie-x.rithb8981.workers.dev/run-bot")

          echo "📦 Full Response:"
          echo "$RESPONSE"

          STATUS_CODE=$(echo "$RESPONSE" | grep "Status:" | awk '{print $2}')
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "❌ API call failed with status $STATUS_CODE"
            exit 1
          else
            echo "✅ API call succeeded with status $STATUS_CODE"
          fi
